### ISSUE TITLE
ImportError: ~/anaconda3/lib/python3.5/site-packages/_icu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_5714LEFontInstanceE

### ISSUE THREAD

**Issue by bilalbayasut** [aboSamoor/polyglot#78]
Can't run polyglot project, please help

ImportError: ~/anaconda3/lib/python3.5/site-packages/_icu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_5714LEFontInstanceE

**Comment by bkj** [comment]
I'm having the same problem, though with Anaconda2. 

```
> uname -a
Linux my-server 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bilalbayasut** [comment]
@bkj have you find the solution ? , I haven't tried uninstall anaconda though... probably anaconda and polyglot don't get along :p

**Comment by bilalbayasut** [comment]
FIXED. I was right, anaconda is somehow conflict with polyglot, thus I uninstall anaconda and just use vanilla python3.5 and it works

**Comment by bkj** [comment]
Can we reopen this?  The issue isn't really resolved.. I've been able to get it to work with Anaconda previously, so it's possible, but there's something funny about it

**Comment by yallapragada** [comment]
Concur - this issue should be reopened. 
I get similar error with anaconda42 when I try to launch polyglot from command line. 

Import error in docs.py:
from _icu import *
ImportError: /home/anaconda42/bin/python3.5/site-packages/_icu.cpython-35m-x86_64-linux-gnu.so:
undefined symbol: _ZNK7icu_4_214LEFontInstance10getSubFontEPKtPiiiR11LEErrorCode

**Comment by amirothman** [comment]
Have you tried with python 3.4 ? I haven't rigorously tested this theory, but I encounter this problem when using Python 3.5 but not with Python 3.4. I don't think this is a Anaconda-specific problem but a Python 3.4 problem. The problem might have something to do with the pycld2 library. [pycld2](https://pypi.python.org/pypi/pycld2/) . And that library is only compatible up to 3.4 (according to its website).

**Comment by yallapragada** [comment]
I have tested polyglot with a conda python 3.4 environment and it works without any issues.

**Comment by bkj** [comment]
The problem still exists for Python 2.7 -- I haven't tried it with Python 3.x

**Comment by bakarov** [comment]
I've downgraded conda environment from 3.5 to 3.4, and I have the same issue.

`anaconda3/lib/python3.4/site-packages/_icu.cpython-34m.so: undefined symbol: _ZTIN6icu_5514LEFontInstanceE`

Also, polyglot for Python 2.7 _without conda_ works fine.

**Comment by bluelight773** [comment]
Same here (as @bakarov).

**Comment by lukewendling** [comment]
Also tried on py 2.7 and 3.5, with conda. same error `undefined symbol: _ZTIN6icu_5514LEFontInstanceE`

**Comment by yallapragada** [comment]
With 3.5 anaconda installed, I created (and activated) a new python 3.4 environment. Installed numpy, polyglot on the top of my 3.4 environment and am able to get it to work.

**Comment by davidvartanian** [comment]
I'VE FOUND A WORKAROUND TO MAKE IT WORK WITH ANACONDA!!

I'm trying to fix it or at least find out why does Anaconda have problems with Polyglot. But The problem is actually not Polyglot or pycld2. The problem is actually between libicu (operating system) and pyicu (python). If you execute `from icu import Locale` you get exactly the same error:

> /home/david/anaconda3/envs/py34/lib/python3.4/site-packages/_icu.cpython-34m.so: undefined symbol: _ZTIN6icu_5414LEFontInstanceE

What I've tried:

- Installing all `icu` packages available on conda (from all channels, for the version 54.1)
- Building the python package by my own from ICU's source code (https://pypi.python.org/pypi/PyICU/) with exactly the same results.
- Using the file xxx.so created by the operating system's package: this way it works fine!

So what's the workaround?

1. Install the operating system's packages: `sudo apt install python3-icu libicu57 icu-devtools` (package names may be different on other operating systems, I'm using Ubuntu 16.10)
2. Install python's icu with conda: `conda install icu=57.1` (it must be the same version your operating system supports, in my case it's 57.1)
3. Delete the .so file generated by conda installer: `rm ~/anaconda3/envs/py34/lib/python3.4/site-packages/_icu.cpython-34m.so`
4. Create a symbolic link to the .so file generated by the operating system package manager: `ln -s /usr/lib/python3/dist-packages/_icu.cpython-35m-x86_64-linux-gnu.so ~/anaconda3/envs/py34/lib/python3.4/site-packages/_icu.cpython-34m.so`

Please notice that I have an environment with Python3.4 on my computer, but Ubuntu's default python3 version is 3.5. It doesn't matter, it works anyway.

**Comment by jennaliu** [comment]
After some digging around, I found out that the issue is caused by incorrect include path to the compiler. You need to either install pyicu with
$ PYICU_INCLUDES=[You anaconda install path]/anaconda3/include setup.py install
or install the latest master from pyicu. It was fixed by this commit https://github.com/ovalhub/pyicu/commit/a6eb3f0abf514cc7b2b21de2bab2c90880aa1af1
